myblog2/myapp/urls.py
from django.urls import path
from myapp import views, feeds

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', feeds.LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

# 實際識別時 : blog:post_list就代表views.post_list

myblog2/myblog2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from myapp import views
from myapp.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('myapp.urls', namespace='blog')), # 因為app叫myapp所以include myapp.urls
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

myblog2/myapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.urls import reverse

# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model): # 貼文
    
    objects = models.Manager()
    published = PublishedManager() # 管理器

    state_choices = {
        ('draft', 'Draft'), 
        ('published', 'Published'),
    }
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20, choices=state_choices, default='draft')

    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)
    def __str__(self):
        return self.title    

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

class Comment(models.Model): # 留言
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    # related_name 解說 : https://blog.csdn.net/hpu_yly_bj/article/details/78939748
    # Post.comment_set.all() 可以查到post對應的comment，而Post.comments.all()也有同樣效果
    name = models.CharField(max_length=80, default='None')
    email = models.EmailField(null=True)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    activate = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Comment by {self.name} on {self.post}'    

myblog2/myapp/forms.py
from django import forms
from myapp import models

class EmailPostFrom(forms.Form):
    name = forms.CharField(max_length=20)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta: # 描述這張表單的情況
        model = models.Comment 
        fields = ('name','body')

class SearchForm(forms.Form):
    query = forms.CharField()        

myblog2/myapp/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.postgres.search import SearchVector
from django.core.mail import send_mail
from django.db.models import Count
from taggit.models import Tag
from myapp import models, forms

# Create your views here.

# CBV
class PostListView(ListView): 
    queryset = models.Post.published.all()
    context_object_name = 'posts' # 把查詢的結果命名為posts，默認是object_list
    paginate_by = 3
    template_name = 'blog/post/list.html'


# FBV
def post_list(request, tag_slug=None):
    object_list = models.Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)
    page = request.GET.get('page') # 因為在pagination.html中寫了?page=...所以page變成傳遞參數
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)        
    return render(request, 'blog/post/list.html', locals())

def post_detail(request, year, month, day, post):
    post = get_object_or_404(models.Post, 
                                slug=post, status='published', 
                                publish__year=year, 
                                publish__month=month, 
                                publish__day=day)
    post_tags_id = post.tags.values_list('id', flat=True) # 取得該篇post所有的tag
    similar_posts = models.Post.published.filter(tags__in=post_tags_id).exclude(id=post.id) # 取得所有相關tag的發文，但不含本篇
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    # similar_posts.annotate(same_tags=Count('tags')) 意思是: 讓有相關的post計算自己自身的tag，假設A本身有4個tags那A的same_tags=4
    # 之後再和tags數、publish排順序

    comments = post.comments.filter(activate=True) #post.comments.filter(activte=True) = models.Comment.objects.filter(post=post, activate=True)                            
    new_comment = None # 這是新留言的，comments是之前的留言
    if request.method == 'POST':
        comment_form = forms.CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = forms.CommentForm()

    return render(request, 'blog/post/detail.html', locals())

def post_share(request, post_id):
    post = get_object_or_404(models.Post, id=post_id, status='published') # 有去向資料庫要資料
    sent = False
    if request.method == 'POST':
        form = forms.EmailPostFrom(request.POST)
        if form.is_valid():
            cd = form.cleaned_data # 取出資料 資料以字典儲存
            # send email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url} ， {cd['name']} comments: {cd['comments']}"
            send_mail(subject, message, 's1071531@gm.pu.edu.tw', [cd['to']])
            sent = True
    else:
        form = forms.EmailPostFrom()
    return render(request, 'blog/post/share.html', locals())

def post_search(request):
    form = forms.SearchForm()
    query = None
    results = []
    if 'query' in request.GET: # query會在Http的報文是因為forms.py定義查詢欄較query
        form = forms.SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = models.Post.objects.annotate(search=SearchVector('title', 'body'),).filter(search=query)
            # 查詢文章title，body的column，這兩個是自訂義 
    return render(request, 'blog/post/search.html', locals())
    # ?query=查詢資料，所以查詢後網址的變化，(查詢資料)就是輸入的資料      

myblog2/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static 'css/blog.css' %}" rel='stylesheet'>
        <!--<link href='static/css/blog.css'>-->
    </head>
    <body>
        <div id='content'>
            {% block content %}{% endblock %}
        </div>
        <div id='sidebar'>
            <h2>My Blog</h2>
            <p>This is My Blog. I've written {% total_posts %} posts so far.</p>
            
            <h3>Latest Posts</h3>
            {% show_latest_posts 3 %}
            
            <h3>Most commented posts</h3>
            {% get_most_commented_posts as most_commented_posts %} <!--把get_most_commented_posts的結果存到most_commented_posts-->
            <ul>
                {% for post in most_commented_posts %}
                    <li>
                        <a href="{{post.get_absolute_url}}">Title : {{post.title}}</a>
                    </li>
                {% endfor %}
            </ul>
            <p>
                <a href="{% url 'blog:post_feed' %}">Subscribe to my RSS</a>
            </p>    
        </div>
    </body>
</html>

myblog2/templates/blog/pagination.html
<div class='pagination'>
    <span class='step-links'>
        {% if page.has_previous %}
            <a href="?page={{page.previous_page_number}}">Previous</a>
        {%endif%}
        <span class='current'>
            Page {{page.number}} of {{page.paginator.num_pages}} .
        </span>
        {% if page.has_next %}
            <a href="?page={{page.next_page_number}}">Next</a>
        {% endif %}    
    </span>
</div>

myblog2/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}{{post.title}}{% endblock %}

{% block content %}
    <h1>{{post.title}}</h1>
    <p class='date'>
        Published {{post.publish}} by {{post.author}}
    </p>
    <!--{{post.body | linebreaks}}-->
    {{post.body | markdown}}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">
            Share this post
        </a>
    </p>
    
    <!--顯示有多少留言-->
    {% with comments.count as total_comments %}
        <h2>
            {{total_comments}} comment 
        </h2>
    {% endwith %}
    
    <!--所有留言-->
    {% for comment in comments %}
        <div class='comment'>
            <p class='info'>
                Comment {{forloop.counter}} by {{comment.name}}
                {{comment.created}}
            </p>
            {{comment.body | linebreaks}}
        </div>
        {% empty %}
            <p>There is no comment.</p>
    {% endfor %}
    
    <!--新留言-->
    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form method="post">
            {% csrf_token %}
            {{comment_form.as_p }}
            <p><input type='submit' value='add comment'></p>
        </form>
        
    {% endif %}


    <!--類似的comment-->
    <h2>Similar Post</h2>
    {% for post in similar_posts %}
        <p>
            <a href='{{post.get_absolute_url}}'>{{post.title}}</a>
        </p>
    {% empty %}
        There is no similar comment.
    {% endfor %}

{% endblock %}

myblog2/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{post.get_absolute_url}}">{{post.title}}</a>
        </li>
    {% endfor %}
</ul>

myblog2/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}My Blog{% endblock %}

{% block content %}
    <h1>My Blog</h1>

    {% if tag %}
        <h2>Posts tagged with {{tag.name}}</h2>
    {% endif %}
    
    {% for post in posts %}
        <h2>
            <a href="{{post.get_absolute_url}}">Title : {{post.title}}</a>
            <!--當我點title時，models.Post.get_absolute_url裡傳遞的self就是指post這個物件-->
            <p class='tags'>
                Tags :
                {% for tag in post.tags.all %}
                    <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{tag.name}}</a> <!--blog是namespace-->
                    {% if not forloop.last %}{% endif %}
                {% endfor %}
            </p>
        </h2>
        <p class='date'>
            Published {{post.publish}} by {{post.author}}
        </p>
        <!--{{post.body | truncatewords:30 | linebreaks}}-->
        {{post.body | markdown | truncatewords_html:30 }}
    {% endfor %}
    
    <!--{% include "blog/pagination.html" with page=posts %}--> <!--with 攜帶參數-->
    {% include "blog/pagination.html" with page=posts %}
{% endblock %}

myblog2/templates/blog/post/search.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}Search{% endblock %}

{% block content %}
    {% if query %} <!--查詢結果-->
        <h1>Post Containing {{query}}</h1>
        <h3> <!--查詢數量-->
            {% with results.count as total_results %}
                Found {{total_results}} result {{total_result | pluralize}}
            {% endwith %}
        </h3>
        {% for post in results %} <!--查詢的內容-->
            <h4><a href="{{post.get_absolute_url}}">{{post.title}}</a></h4>
            {{post.body|markdown|truncatewords_html:5}}
        {% empty %} <!--沒有查詢內容-->
            <p>There are not result for your query</p>
        {% endfor %}
    {% else %} <!--剛開始查詢-->
        <h1>Search for posts</h1>
        <form method="get">
            {{form.as_p}}
            <input type='submit' value='Search'>
        </form>
    {% endif %}
{% endblock %}

myblog2/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            {{post.title}} was send to {{form.cleaned_data.to}} .
        </p>
    {% else %}
        <h1>Share {{post.title}} by Email</h1>
        <form method='post'>
            {{form.as_p}}
            {% csrf_token %}
            <input type='submit' value='send_email'>
        </form>    
    {% endif %}
{% endblock %}